/*
 * Decompiled with CFR 0_122.
 * 
 * Could not load the following classes:
 *  br.gov.sp.fazenda.dsen.common.enumeration.GrupoNotificacaoEnum
 *  br.gov.sp.fazenda.dsge.common.enumeration.EnumItf
 */
package br.gov.sp.fazenda.dsen.common.enumeration;

import br.gov.sp.fazenda.dsge.common.enumeration.EnumItf;

public enum GrupoNotificacaoEnum implements EnumItf
{
    ERRO_FATAL,
    EXCEPTION,
    UF_NAO_HABILITADA,
    ERRO_RESPOSTA_SEFAZ_BUSCA_RETORNO,
    ERRO_RESPOSTA_SCAN_BUSCA_RETORNO,
    BUSCA_RETORNO_CONHECIMENTO,
    BUSCA_RETORNO_TOTAL,
    BUSCA_RETORNO_PROCESSADAS,
    BUSCA_RETORNO_PROBLEMAS,
    ERRO_RESPOSTA_SEFAZ_CONSULTA_STATUS,
    ERRO_RESPOSTA_SCAN_CONSULTA_STATUS,
    CONSULTA_STATUS_SERVICO_NOK_SEFAZ,
    CONSULTA_STATUS_SERVICO_NOK_SCAN,
    ERRO_RESPOSTA_SEFAZ_ENVIO,
    ERRO_RESPOSTA_SCAN_ENVIO,
    NOTA_FISCAL_ENVIADA,
    ERRO_CONEXAO_ENVIO_SEFAZ,
    ERRO_CONEXAO_ENVIO_SCAN,
    ERRO_RESPOSTA_SEFAZ_CONSULTA_NOTA_FISCAL,
    ERRO_RESPOSTA_SCAN_CONSULTA_NOTA_FISCAL,
    NOTA_FISCAL_CONSULTADA,
    CONSULTA_NOTA_FISCAL_ERRO_SEFAZ,
    CONSULTA_NOTA_FISCAL_ERRO_SCAN,
    ERRO_RESPOSTA_SEFAZ_INUTILIZACAO,
    ERRO_RESPOSTA_SCAN_INUTILIZACAO,
    INUTILIZACAO,
    INUTILIZACAO_ERRO_SEFAZ,
    INUTILIZACAO_ERRO_SCAN,
    ERRO_RESPOSTA_SEFAZ_CANCELAMENTO,
    ERRO_RESPOSTA_SCAN_CANCELAMENTO,
    CANCELAMENTO,
    CANCELAMENTO_ERRO_SEFAZ,
    CANCELAMENTO_ERRO_SCAN,
    ERRO_RESPOSTA_DPEC_ENVIO,
    ERRO_RESPOSTA_DPEC_CONSULTA,
    DPEC_RESULTADO,
    DPEC_TOTAIS,
    ENVIO_DPEC,
    ENVIO_DPEC_ERRO,
    CONSULTA_DPEC,
    CONSULTA_DPEC_ERRO,
    DPEC_SALVAR,
    CONSULTA_CADASTRO_ERRO,
    ERRO_RESPOSTA_CONSULTA_CADASTRO,
    IMPORTACAO_TIPO_AMBIENTE_DIFERENTE,
    IMPORTACAO_DUPLICIDADE_REGISTRO,
    IMPORTACAO_ASSINATURA_INVALIDA,
    CERTIFICADO_BUSCA_AUTOMATICA_ARQUIVO_LIDO,
    CERTIFICADO_SENHA_A3,
    CERTIFICADO_SENHA_ERRADA_A3,
    EVENTO_ENVIADO,
    ERRO_RESPOSTA_SEFAZ_EVENTO,
    ERRO_RESPOSTA_SCAN_EVENTO,
    ERRO_CONEXAO_EVENTO_SEFAZ,
    ERRO_CONEXAO_EVENTO_SCAN;
    

    private GrupoNotificacaoEnum() {
    }
}

